language: python
sudo: false
python:
 - "2.7"
 - "3.4"
 - "3.5"
 - "3.6"
env:
  global:
   - DRF="djangorestframework==3.6.3"
   - WQIO="wq.io==1.0.0b1"
  matrix:
   - DJANGO="django==1.8.18"
   - DJANGO="django==1.8.18" WITH_WQDB="pip install wq.db==1.0.0rc1"
   - DJANGO="django==1.11.1"
   - DJANGO="django==1.11.1" WITH_WQDB="pip install wq.db==1.0.0rc1"
   - DJANGO="django==1.11.1" WITH_WQDB="pip install wq.db==1.0.0rc1" WITH_REVERSION="pip install django-reversion"
   - DJANGO="django==1.11.1" LINT="pip install flake8"
before_script:
 - createdb -Upostgres data_wizard_test
 - psql -Upostgres data_wizard_test -c "CREATE EXTENSION postgis;"
install:
 - pip install $DJANGO $DRF
 - pip install $WQIO
 - pip install psycopg2
 - pip install .
 - $WITH_WQDB
 - $WITH_REVERSION
 - $LINT
script:
 - ./runtests.sh
services:
 - redis-server
