language: python
sudo: false
python:
 - "2.7"
 - "3.4"
env:
  global:
   - DRF="djangorestframework==3.3.2"
   - WQDB="git+https://github.com/wq/wq.db.git"
   - WQIO="wq.io==0.8.0"
   - VERA="git+https://github.com/wq/vera.git"
  matrix:
   - DJANGO="django==1.8.8"
   - DJANGO="django==1.8.8" LINT=1
before_script:
 - createdb -Upostgres data_wizard_test
 - psql -Upostgres data_wizard_test -c "CREATE EXTENSION postgis;"
install:
 - pip install $DJANGO
 - pip install $DRF
 - pip install $WQDB
 - pip install $WQIO
 - pip install $VERA
 - pip install flake8
script:
 - ./runtests.sh
services:
 - redis-server
