language: python
dist: xenial
env:
  global:
    - DRF="djangorestframework==3.9.1"
    - DJANGO="django==2.1.7"
    - WQIO="wq.io==1.1.0"
matrix:
  include:
    - python: "2.7"
      env:
        - DJANGO="django==1.8.19"
        - DRF="djangorestframework==3.6.4"
    - python: "3.5"
      env:
        - DJANGO="django==1.8.19"
        - DRF="djangorestframework==3.6.4"
    - python: "2.7"
      env:
        - DJANGO="django==1.11.20"
    - python: "3.7"
      env:
        - DJANGO="django==1.11.20"
    - python: "3.4"
      env:
        - DJANGO="django==2.0.13"
    - python: "3.5"
      env: []
    - python: "3.6"
      env: []
    - python: "3.7"
      env: []
    - python: "3.7"
      env:
        - WQDB="wq.db==1.1.2"
    - python: "3.7"
      env:
        - WQDB="wq.db==1.1.2"
        - REVERSION="django-reversion"
    - python: "3.7"
      env:
        - LINT="flake8"
before_script:
 - createdb -Upostgres data_wizard_test
 - psql -Upostgres data_wizard_test -c "CREATE EXTENSION postgis;"
install:
 - pip install $DJANGO $DRF $WQIO $WQDB $REVERSION $LINT
 - pip install psycopg2
 - pip install .
script:
 - ./runtests.sh
services:
 - redis-server
addons:
  postgresql: "10"
  apt:
    packages:
     - postgresql-10-postgis-2.4
