language: python
dist: xenial
python:
 - "2.7"
 - "3.4"
 - "3.5"
 - "3.6"
 - "3.7"
env:
  global:
   - DRF="djangorestframework==3.9.1"
   - WQIO="wq.io==1.1.0"
  matrix:
   - DJANGO="django==1.8.19"
   - DJANGO="django==1.11.20"
   - DJANGO="django==2.0.13"
   - DJANGO="django==2.1.7"
   - DJANGO="django==2.1.7" WQDB="wq.db==1.1.2"
   - DJANGO="django==2.1.7" WQDB="wq.db==1.1.2" REVERSION="django-reversion"
   - LINT="flake8"
before_script:
 - createdb -Upostgres data_wizard_test
 - psql -Upostgres data_wizard_test -c "CREATE EXTENSION postgis;"
install:
 - pip install $DJANGO $DRF $WQIO $WQDB $REVERSION $LINT
 - pip install psycopg2
 - pip install .
 - $LINT
script:
 - ./runtests.sh
services:
 - redis-server
addons:
  postgresql: "10"
  apt:
    packages:
     - postgresql-10-postgis-2.4
