language: python
sudo: false
python:
 - "2.7"
 - "3.4"
 - "3.5"
env:
  global:
   - DRF="djangorestframework==3.5.1"
   - CELERY="celery==4.0.0rc3"
   - KOMBU="kombu==4.0.0rc3"
   - WQDB="https://github.com/wq/wq.db/archive/master.zip"
   - WQIO="wq.io==1.0.0b1"
   - VERA="https://github.com/wq/vera/archive/master.zip"
  matrix:
   - DJANGO="django==1.8.15"
   - DJANGO="django==1.9.10"
   - DJANGO="django==1.10.2"
   - DJANGO="django==1.10.2" LINT=1
before_script:
 - createdb -Upostgres data_wizard_test
 - psql -Upostgres data_wizard_test -c "CREATE EXTENSION postgis;"
install:
 - pip install $DJANGO $DRF
 - pip install $CELERY $KOMBU
 - pip install https://github.com/wq/django-natural-keys/archive/master.zip
 - pip install $WQDB $WQIO $VERA
 - pip install psycopg2 Pillow
 - pip install flake8
 - pip install .
script:
 - ./runtests.sh
services:
 - redis-server
