language: python
sudo: false
python:
 - "2.7"
 - "3.4"
env:
  global:
   - DRF="djangorestframework==3.2.3"
   - WQDB="git+https://github.com/wq/wq.db.git"
   - WQIO="git+https://github.com/wq/wq.io.git"
   - VERA="git+https://github.com/wq/vera.git"
  matrix:
   - DJANGO="django==1.7.10"
   - DJANGO="django==1.8.4"
   - DJANGO="django==1.8.4" LINT=1
before_script:
 - createdb -Upostgres data_wizard_test
 - psql -Upostgres data_wizard_test -c "CREATE EXTENSION postgis;"
install:
 - pip install $DJANGO
 - pip install $DRF
 - pip install $WQDB
 - pip install $WQIO
 - pip install $VERA
 - pip install flake8
script:
 - ./runtests.sh
services:
 - redis-server
