language: python
sudo: false
python:
 - "2.7"
 - "3.4"
 - "3.5"
env:
  global:
   - DRF="djangorestframework==3.4.6"
   - CELERY="celery==4.0.0rc3"
   - KOMBU="kombu==4.0.0rc3"
   - WQDB="wq.db==1.0.0b2"
   - WQIO="wq.io==1.0.0b1"
   - VERA="vera==1.0.0b1"
  matrix:
   - DJANGO="django==1.8.14"
   - DJANGO="django==1.9.9"
   - DJANGO="django==1.10.1"
   - DJANGO="django==1.10.1" LINT=1
before_script:
 - createdb -Upostgres data_wizard_test
 - psql -Upostgres data_wizard_test -c "CREATE EXTENSION postgis;"
install:
 - pip install $DJANGO $DRF
 - pip install $CELERY $KOMBU
 - pip install $WQDB $WQIO $VERA
 - pip install flake8
script:
 - ./runtests.sh
services:
 - redis-server
